name: "publish package to npm"

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: get local version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          local=$(node -p "require('./package.json').version")
          npm=$(npm view @suzu-sys/aws-auth-notion-cli version)
          if [ $local = $npm ]; then
            npm version patch
            next=$(git add package.json package-lock.json)
            git push origin $next
          fi
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
