name: "publish package to npm"

on:
  pull_request:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: get local version
        run: local=$(node -p "require('./package.json').version")
      - name: get npm remote version
        run: npm=$(npm view @suzu-sys/aws-auth-notion-cli version)
      - name: test
        run: echo $local
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
