name: "test package"

on:
  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - "src/"
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    if: ${{  github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm test
